# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dashboard.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class DashboardRegister(betterproto.Message):
    user_id: int = betterproto.int32_field(1)
    image: str = betterproto.string_field(2)
    label: int = betterproto.int32_field(3)
    confidence: float = betterproto.float_field(4)


@dataclass
class DashboardProto(betterproto.Message):
    id: int = betterproto.int32_field(1)
    image: str = betterproto.string_field(2)
    label: int = betterproto.int32_field(3)
    confidence: float = betterproto.float_field(4)
    user_id: int = betterproto.int32_field(5)
    created_at: str = betterproto.string_field(6)


@dataclass
class DashboardResponse(betterproto.Message):
    detail: str = betterproto.string_field(1)


@dataclass
class DashboardList(betterproto.Message):
    data: List["DashboardProto"] = betterproto.message_field(1)
