"""create users database

Revision ID: 1ab318deb986
Revises: 
Create Date: 2025-10-01 16:21:58.065764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import INTEGER, VARCHAR, NVARCHAR, Column, DATETIME
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = '1ab318deb986'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        Column("id", INTEGER, primary_key=True, autoincrement=True),
        Column("name", VARCHAR(255), nullable=False),
        Column("username", VARCHAR(255), nullable=False),
        Column("password", NVARCHAR(255), nullable=False),
        Column("created_at", DATETIME, server_default=str(datetime.now())),
    )
    op.create_unique_constraint("unique_user_username", "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
