"""create logs table

Revision ID: 1da2bbc8a66e
Revises: f0697702fed7
Create Date: 2025-10-07 13:54:36.514365

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import ForeignKey
from sqlalchemy import INTEGER, VARCHAR, Column, DATETIME
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = '1da2bbc8a66e'
down_revision: Union[str, Sequence[str], None] = 'f0697702fed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logs",
        Column("id", INTEGER, primary_key=True, autoincrement=True),
        Column("category", VARCHAR(255), nullable=False),
        Column("color", VARCHAR(255), nullable=False),
        Column("status", VARCHAR(255), nullable=False),
        Column("user_id", INTEGER, ForeignKey('users.id')),
        Column("created_at", DATETIME, server_default=str(datetime.now())),
    )

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("logs")
    # ### end Alembic commands ###
