"""Added dashboards table

Revision ID: f0697702fed7
Revises: 1ab318deb986
Create Date: 2025-10-06 16:46:32.425232

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import ForeignKey
from sqlalchemy import INTEGER, VARCHAR, Column, DATETIME
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = 'f0697702fed7'
down_revision: Union[str, Sequence[str], None] = '1ab318deb986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    """Downgrade schema."""
    op.create_table('dashboards',
    Column("id", INTEGER, primary_key=True, autoincrement=True),
    Column('image', VARCHAR(length=255), nullable=False),
    Column('label', INTEGER, nullable=True),
    Column('confidence', INTEGER, nullable=True),
    Column("user_id", INTEGER, ForeignKey('users.id')),
    Column('created_at', DATETIME, server_default=str(datetime.now()), nullable=False),
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dashboards")
    # ### end Alembic commands ###