# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: auth.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class LoggedUser(betterproto.Message):
    id: int = betterproto.int32_field(1)
    name: str = betterproto.string_field(2)
    username: str = betterproto.string_field(3)


@dataclass
class PotentialUser(betterproto.Message):
    username: str = betterproto.string_field(1)
    password: str = betterproto.string_field(2)


@dataclass
class Register(betterproto.Message):
    name: str = betterproto.string_field(1)
    username: str = betterproto.string_field(2)
    password: str = betterproto.string_field(3)


@dataclass
class RegisterResponse(betterproto.Message):
    detail: str = betterproto.string_field(2)
