# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: log.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class LogRegister(betterproto.Message):
    user_id: int = betterproto.int32_field(1)
    category: str = betterproto.string_field(2)
    color: str = betterproto.string_field(3)
    status: str = betterproto.string_field(4)


@dataclass
class LogProto(betterproto.Message):
    id: int = betterproto.int32_field(1)
    category: str = betterproto.string_field(2)
    color: str = betterproto.string_field(3)
    status: str = betterproto.string_field(4)
    user_id: int = betterproto.int32_field(5)
    created_at: str = betterproto.string_field(6)


@dataclass
class LogResponse(betterproto.Message):
    detail: str = betterproto.string_field(1)


@dataclass
class LogList(betterproto.Message):
    data: List["LogProto"] = betterproto.message_field(1)
